const subjects = ['General Ability', 'Current Affairs', 'Reasoning', 'Quantitative Aptitude'];

function generateQuestions({ count = 10, subject }) {
  return Array.from({ length: count }).map((_, i) => ({
    subject: subject || subjects[i % subjects.length],
    questionText: `AI Generated Q${i + 1}: Sample CAPF concept check?`,
    options: ['Option A', 'Option B', 'Option C', 'Option D'],
    correctOptionIndex: i % 4,
    solution: 'This is an autogenerated placeholder solution.',
    source: 'ai-generated'
  }));
}

module.exports = { generateQuestions };
